# Generated by Django 4.1.7 on 2023-03-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
